### ISSUE TITLE
Github Auth Needed For Basic Operations

### ISSUE THREAD

**Issue by vsoch** [alecbcs/lookout#2]
I'm trying to reproduce the example you showed me, I tried for both singularity and the example in the README, both don't work!

```bash
$ ./lookout add cuppa 1.1.0 https://github.com/DataDrake/cuppa/archive/v1.1.0.tar.gz
2020/10/02 17:26:40 Unable to find cuppa https://github.com/DataDrake/cuppa/archive/v1.1.0.tar.gz
```
I think I'm probably forgetting something... I shouldn't need to export a GitHub token for using the API, and if I did need to, there would be a warning right? What am I forgetting?

```bash
$ ./lookout add singularity 3.6.3 https://github.com/hpcng/singularity/releases/download/v3.6.3
2020/10/02 17:25:58 Unable to find singularity https://github.com/hpcng/singularity/releases/download/v3.6.3
```

**Comment by alecbcs** [comment]
Hey @vsoch! I'd try adding a personal access token for GitHub. GitHub likes to just return to Lookout that an application doesn't exist sometimes at an anti-spam measure. This didn't happen super frequently before, but I just tested this out and I can confirm that without an access token, GitHub just pretends the repository in question doesn't exist. I'll check into the extent of this issue and see if there might be a work around to either using another API or to tell the user to import a key.

**Comment by vsoch** [comment]
Ah, makes sense! Actually this might be a fun way for me to do my first PR, would it be okay if I gave it a shot? I was able to free up some time this weekend and I'm super wanting to start on this!

**Comment by alecbcs** [comment]
Absolutely! If we for sure need personal access tokens for access to GitHub, we might be able to use Github's Oath system to provide users with a simple click --> authorize lookout in a browser --> save key to lookout and finish the command.
